language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: j/egWLEyuaeEwuaT8JTS30kYKV1oqfg7NG/fd5zWaSv2KOWcO8StuA3YKeddAyHvbpa/uLkg/RE/WDfighIxfcmgvlGOt1OfFx+KXUMU2Y5vPBhk/R3CS2EYNYQx7cGkURqJZQKV/6toDY9IRabx+DSpkGL0z/XdfldBPIIKkvROC59vkv+vbFhHTyXfd63ZHJDuDRYM8W8bnxK1ENCHL0nSZIfAT20S9ZV+tIPbKxWdoFG4Y87d2+h8lh+GkFYrS89PsTMWS4nHgXHT5it6BQCmVTH+h7FlmeWMMiWU9PvRI5VCaXlu1z1ydmZdQJe88D7Fl6dY6SDvrhEcob+PRDUMCRje6mjeljQK0gtcOuiDNr1Sfu83fIjYaX9MrJAzariXiKDtLlMpt6QzK5GEBaoaA7kT43mS/mTQ7Tcj4xOxTcxuz6a5U8u1rKy8kCypax+yI0NTzN5iywRvaW7fqlkk9j0UTDrWxjbiA63yyMV8Sa5VJq3Dz1abqgeO5MrbJh1VzRovcLhRtuedvL4hiKlLMWIE3dTWrFLql0B/SgFBdIvPHjtdPShPusNc5IFO98S9/In7butFwfEgiuAeaCwaL9nWWfRR5NnFz60Sv0t+e6LH8GuDoi/77Sk21yk5bcQy/MzrgArv79N3RtwGDYukTrlrK5hQtrB+JOhR0/E=
  app: infinite-castle-97006
  on:
    repo: AndrewPark9517/react-trello-testing
