language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: veWmeYyqRLKVbNWNO6+BTe+hFTo3ilbRpvwfBzEZ67VB+oDUfS1dCAOARRcnISYyDd8HPfkc/+/HdVc/B0D/s65VrYe+L927AEE5scyZSezLvRTZ49tjkwpK7K44NQAV6uskiZouw2lsLNvWAIgzu2V3+s5M8qHskShJilaXLd2dHTqNcpgjzwqeo8OKa2hY42ec1HiajhJe9eddBvr27qJXnlQqeIBNQSW12gwFwcUpxFpbd03xOWayozD+cnyFxMxdlkPoh/2AJY+1vuhlhchJBCdltQ95GTgUlxqyjdVmpSqd25j6F+jPBHF1LVvhb7E2In+tul9u4sg1vMz/SSLMkefcFn5wcYdjcRlYobhmBMX/INxudal65G3zc5coPJLIZ01q+nOS7zMN9H4lALjdXQYTKV0tngvY492ijvV1HZ5j2Wd0w5V3j+zUIqL5CEbpA2ct0+8IqcTEGe4jt6t2wVqWlV+tiXmqutA/LFo1XVzibz24G516P+jqIT9AnnZEghR8jyAv+05jflPgzTT7WqkJ2ZqwFO6LJ9U+3HcVHYgBPBAR65o4uaamfIqfdfz1VPC4PFmi+DsmlCMKY67eIp3vnyapMG03UzpbdpmoYkVeLsk0GL8BxtskBUuqVjLhrwWiDaaa5XkeTC9J8VYxTzJPHOkk9YmU903h778=
  app: react-trello-testing
  on:
    repo: AndrewPark9517/react-trello-testing
