language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: ovQpiE4vA8xnA6la149yzJprrv1Npd0JcrtKgn62CucVnipIG7TV70R5C77RWIMdwAbfZ2OlyIdBBT/n+EFd3t5iyVQ4CxML0i4LeMKRTpVVH8ccSQpF1Ro9sDRPlid3cO9k8YbaQWLhCTujR2Sshk9/mM2YP73oeCOr3D1xzv9h/mzKuWmeKg/6gdkFb1kOUTgGN0yDYr2W2OgaeIUr4EIXdBpnmnssOK0/WW3ms0+K0WCFyvaLKW7H1MZw/ryL3ljNIC5P7zC+PJa56Lk2YfSmyad8P2JmrQphcvkDPcKj1v0jMc1xpthj+UGiI/nEywkUgNSRirt+au59rLhe16d611pui1ezHUTqSm79c/bFgSrPPWvaj0gNHCblCMHzgGtWUVvQjIwpkBA4Gt3fhfuxgZ4rwQkvaukPjqyyBfJtHqz1p1LdKidBulQAD6sBvTYtBICW6L3z4hJY0PJLS+0xzfVRz/838aRLuHZaKmQxjPX7lCYsGt9oiKnOdZuId0pwqXsR3dCmjl4g+s0+zjD52MF4cAtvfWjQHEnF4v0Teppn1ecFjjBkmGyd/AKNDcvOOtPtjQ9bbNLi9hD717/oMX0aH4qVyWkbUN2qVWGCOXMfhUAoLZH53f50KvKVIkN7p0agdWS4j1tdMjmN7uRpgE3eRwRjAKvh1bNCtFo=
  app: infinite-castle-97006
  on:
    repo: AndrewPark9517/react-trello-testing
