language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: stALAyOS9D4S7/s7ZL2n09HKAvCcZbo2j4C1MHig1qtCRBLFPWNDj8RLsWIV3osrQ5Tuw4clzhTE2BschiK2NfR4OleM4CXqlMOXhZO+XsiqtsZ28AnG4IZ6VRepNPVSZSMotl2nGIdjGIc+pu3b7EE3UZPnLmOQ5dJfJ7zLoo65hA95Dd1VIYuP88vHxfD74Sd2EytDoju6K1yDALi6ZRPpTgjw5vuQYeQ4kfPv4LWK60NlOOLy45ffnMl8UufkBRla6lc0PwW00C5NJ5n2X2jCqBwDwvUaGzQrZI31M+qPuz8VotDg05u9Ueds+Lt9MhM3UMk8JECh+KuAIGoTeQOpBX3hwIgDpGUyCmSLUnhwQ6zUxhnQ0fwEbVdfE3wEUl2AtT9pbv3BxNmXTaM0s0fyjtMFUhYcdXokT7Eteh/r9Uq7JEOonLQa4DkzcTIVOZ5qCI0EzBgzzTx0RBB/TBnt7hhPk/Fc+E/iMPU+16OrvAS7oSCVt5mDBQk7qxTHZwbCymWz34wVKZXr2AnSq3yEyCpOPyyRbnvTSz9QMcxnyFoF/zZIAgxAJfGZmoyRQk+HizsgAWO7agJUMVquGBF6AG3n25DTSWHknl0qcSmgzi9qNWtZWEfgZ/qMWmFZXJPiKb88Zdhgxj9zWmZ5Seg7mgpVYaj7ai5I7Lu1Lmg=
  app: infinite-castle-97006
  on:
    repo: AndrewPark9517/react-trello-testing
